INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Robert','robert@example.com','$2a$10$gllBMEF.4cCv4wpo2qlv7OEpL8necFDx65PeY8mn2frV664b2PyaS','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Admin','admin@example.com','$2a$10$gllBMEF.4cCv4wpo2qlv7OEpL8necFDx65PeY8mn2frV664b2PyaS','Administrateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Jack','jack@example.com','$2a$10$gllBMEF.4cCv4wpo2qlv7OEpL8necFDx65PeY8mn2frV664b2PyaS','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Payment','paymentUser@dukesforest.com','sha1:64000:18:qlmDg8C4+X7BBGg0QIRo3wojbrndS+W8:iYm4Qil6xlHetLr8oDZdkFD0','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Robert','robert@exampl.com','sha1:64000:18:ICJ4FayH4OF8Z3tP4bODu9yEYeBQCs3Q:aYNM6Qn25ajJ82bU56XEOAqI','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Admin','admin@exampl.com','sha1:64000:18:vmLhsijjCCHf5LMnY2xU+hX89SAVQa5t:/eqLMsCzP82JREWNJbpQWKpI','Administrateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Jack','jack@exampl.com','sha1:64000:18:j1FV0cNg4yQd3/3l54C2j3sU5v9cNdBq:LXF0+rVbJlI2YZ/NygTlQOYt','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Payment','paymentUser@dukesfores.com','sha1:64000:18:PpXe/BDWk0Pgqa0/rx7IN5F135BnFzTQ:HRjEZTWP39hVJoBxww6oDQfw','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Robert','robert@examp.com','sha1:64000:18:DyId44zZz6HOQp1UFcXwWCGcwb4oRd0v:rL2wsRse3TodYyqc36Tj80UD','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Admin','admin@examp.com','sha1:64000:18:RMwp/vgXzdvCmB4AiH9OURVlRqqiD1D3:GirfmfVZM72zZrDrhTBADoGS','Administrateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Jack','jack@examp.com','sha1:64000:18:lmbR9mGAnY53z1sClEhaFDb1kSujUnLZ:rl9Ds9GKg2Gvr6vh6LXSFY2M','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Payment','paymentUser@dukesfore.com','sha1:64000:18:S6GL8m+Yg3N3ZlJWtzHAEXAqqHb/qbws:/x6CYcllcoUdR0sDCeV5seUA','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Robert','robert@xample.com','sha1:64000:18:rg8bB8BKU/wMH1W1KRSvP1pQOnQeSU+6:sCVN/6sQCt1MuBZoVFsbN7ch','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Admin','admin@xample.com','sha1:64000:18:ntmZ3oGpJwX9RFzORaW/zSkOsSGptQ3v:De/T48WkR+IcJWjM1ROCzVk0','Administrateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Jack','jack@xample.com','sha1:64000:18:ukuNJ54u2dRuRuwyRY4cnQB+EGPXDTw0:XIMQylP+EhwTaNdgqlQgQFsU','Utilisateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Duke','duke','$2a$10$gllBMEF.4cCv4wpo2qlv7OEpL8necFDx65PeY8mn2frV664b2PyaS','Administrateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('Admin','admin','$2a$10$rYuY0bMvuxihQHSIA1WHYOM4niCccA58ZKuOSGqpvESlT0BBQLlC.','Administrateur');
INSERT INTO PROFIL (NOM,EMAIL,MDP,DTYPE) VALUES ('User','user','$2a$10$cZJ.MxGi00YnJO8ds3SJV.xHozpz2sJYru3mnInQnu0YhXubXRnmi','Utilisateur');

INSERT INTO GROUPES (NOM, DESCRIPTION) VALUES ('USER', 'Utilisateurs du site.');
INSERT INTO GROUPES (NOM, DESCRIPTION) VALUES ('ADMIN', 'Administrateur du site.');

INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (1,1);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (2,2);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (1,3);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (1,4);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (2,16);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (2,17);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (1,18);
INSERT INTO PROFIL_GROUPES (ID_GROUPES,ID_PROFIL) VALUES (2,6);

INSERT INTO ENTREPRISE (RAISON_SOCIALE,FORME_JURIDIQUE,NATURE,SIRET,NUMERO_TVA,ENTREPRISE_ID,PROFIL_ID) VALUES ('Bank s','SAS','Commerciale','12345678901234',NULL,NULL,3);
INSERT INTO ENTREPRISE (RAISON_SOCIALE,FORME_JURIDIQUE,NATURE,SIRET,NUMERO_TVA,ENTREPRISE_ID,PROFIL_ID) VALUES ('Chez Titi','CAPE','Coubeuse','09876543214321',NULL,1,NULL);
INSERT INTO ENTREPRISE (RAISON_SOCIALE,FORME_JURIDIQUE,NATURE,SIRET,NUMERO_TVA,ENTREPRISE_ID,PROFIL_ID) VALUES ('Au marché','SARL','Artisanale','098 765 432 11234',NULL,1,NULL);

INSERT INTO COORDONNEES (RUE,CODE_POSTAL,VILLE,PAYS,EMAIL,TEL,FAX,ENTREPRISE_ID) VALUES ('Avenue dorée','75 001','Paris',NULL,NULL,NULL,NULL,1);
INSERT INTO COORDONNEES (RUE,CODE_POSTAL,VILLE,PAYS,EMAIL,TEL,FAX,ENTREPRISE_ID) VALUES ('6 rue des méditation.','37 520','Décartes',NULL,NULL,NULL,NULL,NULL);
INSERT INTO COORDONNEES (RUE,CODE_POSTAL,VILLE,PAYS,EMAIL,TEL,FAX,ENTREPRISE_ID) VALUES ('102 ruelle sure.','09 082','Bloué sur courge.',NULL,NULL,NULL,NULL,2);
INSERT INTO COORDONNEES (RUE,CODE_POSTAL,VILLE,PAYS,EMAIL,TEL,FAX,ENTREPRISE_ID) VALUES ('Cité des lilas.','98 000','Pleigné',NULL,NULL,NULL,NULL,NULL);
INSERT INTO COORDONNEES (RUE,CODE_POSTAL,VILLE,PAYS,EMAIL,TEL,FAX,ENTREPRISE_ID) VALUES ('24 rue grande.','36 700','Châtillon sur Indre',NULL,NULL,NULL,NULL,3);

INSERT INTO PERSONNE (CIVILITE,NOM,PRENOM,COORDONNEES_ID,ENTREPRISE_ID) VALUES ('Mlle', 'PHILO', 'Sophie', 2, 1);
INSERT INTO PERSONNE (CIVILITE,NOM,PRENOM,COORDONNEES_ID,ENTREPRISE_ID) VALUES ('Mr.', 'ITE', 'Alex', 4, 1);

INSERT INTO DEVIS (NUMERO_DEVIS,DATE_EMISSION,MODE_DE_REGLEMENT,TVA,ACOMPTE,ETAT_DEVIS,ENTREPRISE_ID,PERSONNE_ID) VALUES ('D2021-0001', '30 03 2021', 'Carte bleu', 20, 50, 'Accepté', null, 2);
INSERT INTO DEVIS (NUMERO_DEVIS,DATE_EMISSION,MODE_DE_REGLEMENT,TVA,ACOMPTE,ETAT_DEVIS,ENTREPRISE_ID,PERSONNE_ID) VALUES ('D2021-0002', '31 03 2021', 'Chèque', 5, 0, 'En attente', 2, null);

INSERT INTO LIGNE_DEVIS (DESIGNATION,QUANTITE,PRIX_UNITAIRE,DEVIS_ID) VALUES ('Tours', 2, 200, 1);
INSERT INTO LIGNE_DEVIS (DESIGNATION,QUANTITE,PRIX_UNITAIRE,DEVIS_ID) VALUES ('Montagnes', 1, 2000, 1);
INSERT INTO LIGNE_DEVIS (DESIGNATION,QUANTITE,PRIX_UNITAIRE,DEVIS_ID) VALUES ('Soleil', 2, 200, 2);
INSERT INTO LIGNE_DEVIS (DESIGNATION,QUANTITE,PRIX_UNITAIRE,DEVIS_ID) VALUES ('Trou noir', 1, 2000, 2);

INSERT INTO FACTURE (NUMERO_FACTURE,DATE_EMISSION,DATE_REGLEMENT,MODE_DE_REGLEMENT,TVA,ACOMPTE,ETAT_FACTURE,TYPE,ENTREPRISE_ID,PERSONNE_ID) VALUES ('F2021-0001', '30 04 2021', '30 04 2021', 'Carte bleu', 20, 50, 'Payée', 'Facture', null, 2);
INSERT INTO FACTURE (NUMERO_FACTURE,DATE_EMISSION,DATE_REGLEMENT,MODE_DE_REGLEMENT,TVA,ACOMPTE,ETAT_FACTURE,TYPE,ENTREPRISE_ID,PERSONNE_ID) VALUES ('F2021-0002', '31 04 2021', '31 04 2021','Chèque', 5, 0, 'En attente', 'Facture', 2, null);

INSERT INTO LIGNE_FACTURE (DESIGNATION,QUANTITE,PRIX_UNITAIRE,FACTURE_ID) VALUES ('Tours', 2, 200, 1);
INSERT INTO LIGNE_FACTURE (DESIGNATION,QUANTITE,PRIX_UNITAIRE,FACTURE_ID) VALUES ('Montagnes', 1, 2000, 1);
INSERT INTO LIGNE_FACTURE (DESIGNATION,QUANTITE,PRIX_UNITAIRE,FACTURE_ID) VALUES ('Soleil', 2, 200, 2);
INSERT INTO LIGNE_FACTURE (DESIGNATION,QUANTITE,PRIX_UNITAIRE,FACTURE_ID) VALUES ('Trou noir', 1, 2000, 2);

INSERT INTO NUMEROS_DOCUMENTS (ENTREPRISE_ID,NUMERO_DEVIS,NUMERO_FACTURE) VALUES (1, 2, 2);